#this application.properties file is a standard confiuration file used to \
#store application settings as key-value pairs, \
#primarily for externalized configuration and localization
# e.g database properties such as database url, logging levels or server ports.



spring.application.name=ThreeDaySpring
spring.profiles.active = dev
app.message = Default Message
app.name = Payment Service 
app.version = 1.0
app.timeout = 5000


#basic properties

payment.enabled = True


#retry
Payment.retry.max-attempts = 3
payment.retry.backoff.delay = 1000
payment.retry.backoff.multiplier = 2.0

#Security
payment.security.api-key=secret-key
payment.security.hmac.enabled=true
payment.security.hmac.algorithm=HmacSHA256



